### ISSUE TITLE
Should the Skyvern GUI browser also appear automatically in Windows wsl2?

### ISSUE THREAD

**Issue by SueKim827** [Skyvern-AI/skyvern#145]
I can't see it.

The browser opens with **run_ui.sh**, but nothing happens when I click the button "Execute Task".

**Comment by ykeremy** [comment]
Hi, sorry about that!

This issue (https://github.com/Skyvern-AI/skyvern/issues/128) has some context on the same problem.


If the system you're running Skyvern in, in this case WSL2, doesn't have a GUI running, Skyvern won't just be able to open a "headful" browser. However, you can configure it so that it runs "headless" browser without the GUI from your WSL2.

If you want a headful browser (with a GUI), you can look into this one: https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
