### ISSUE TITLE
Docker Needs to be running 

### ISSUE THREAD

**Issue by johnisanerd** [Skyvern-AI/skyvern#147]
Flagging that docker needs to be running, and that's not covered in the setup instructions.

**Comment by ykeremy** [comment]
Thank you for flagging this! 

Turns out [we just added a log to the setup script](https://github.com/Skyvern-AI/skyvern/blob/999eda9b5d750af6989ccbc9b4ef0a73f7ee8582/setup.sh#L201) 😅 

Would you mind adding a sentence to the quickstart for that one? If not we'll take care of it in the next couple of days.

**Comment by suchintan** [comment]
This is my bad @johnisanerd -- we'd love a quickstart contribution here if you're up for it :)

**Comment by martincarapia** [comment]
@johnisanerd what command did you use to start docker again? Or did you use docker desktop

**Comment by suchintan** [comment]
@martincarapia definitely use docker desktop!

**Comment by martincarapia** [comment]
Ok, because I see online there are CLI ways to run Docker Daemon. Although I believe Desktop is more suitable since it covers Windows, macOS, and Linux
